version: '3'
services:
  backend:
    build:
      context: ./backend
    image: ikmuge/backend
    container_name: ikmuge_backend
    ports:
     - "9000:9000"
    volumes:
      - ./backend/:/home/node/app
      - /home/node/app/node_modules
    environment:
      - PORT=9000
      - APPID=e257c1cee113fe3b59f59c71f09c069f
  frontend:
    build:
      context: frontend
    image: ikmuge/frontend
    container_name: ikmuge_frontend
    environment:
      - PORT=8000
      - ENDPOINT=http://localhost:9000/api
    # volumes:
      - ./frontend/:/home/node/app
      - /home/node/app/node_modules
    ports:
     - "8000:8000"
     - "80:8000"
    depends_on:
      - backend