
- name: initialize
  block:
    - name: clean up docker artifacts
      shell: "docker container prune -f && docker image prune -f"
    - name: ensure directory exists
      become: true
      command: "mkdir -p {{deploy_directory}}"
    - name: change permissions and ownership
      become: true
      file:
        path: "{{deploy_directory}}"
        owner: "{{ansible_user_id}}"
        group: "{{ansible_user_id}}"
        recurse: yes
    - name: clean webroot
      command: "rm -rf {{item}}"
      ignore_errors: yes
      loop:
        - "{{deploy_directory}}*"
  when: "initialize != false"
- name: get updated definition
  git:
    repo: "{{git_repo}}"
    dest: "{{deploy_directory}}"
    clone: yes
    force: yes
    recursive: no
    update: yes
    track_submodules: no
    version: "{{code_env}}"
- name: change backend url
  replace:
    path: "{{deploy_directory}}/docker-compose.yml"
    regexp: 'localhost'
    replace: "{{hostvars[inventory_hostname]['ansible_host']}}"
    backup: no
- name: Tear down existing services
  command: "docker-compose down"
  args:
    chdir: "{{deploy_directory}}"
- name: Create services
  command: "docker-compose build"
  args:
    chdir: "{{deploy_directory}}"
- name: Start services
  command: "docker-compose up -d"
  args:
    chdir: "{{deploy_directory}}"